### PR TITLE
Update for Show/String reform

### PR DESCRIPTION
**Pull request by renato-zannon**
Fallout from the landing on rust-lang/rust#21457

### CODE REVIEW

**Comment by SimonSapin** [comment]
>  Result<_, ()> doesn't implement unwrap anymore 

Does it really not? https://github.com/rust-lang/rust/pull/21457 says:
> The unwrap methods on Result now require Display instead of Debug

**Comment by renato-zannon** [comment]
> Does it really not? rust-lang/rust#21457 says:
> 
>     The unwrap methods on Result now require Display instead of Debug

Yes, that is the reason it does not - `()` only implements `Debug`, not `Display`. The following program does not compile on `rustc 1.0.0-dev (8160fc478 2015-01-22 16:50:17 +0000)`

```rust
fn main() {
    let res: Result<String, ()> = Err(());
    res.unwrap();
}
```

error:
```
foo.rs:3:9: 3:17 error: type `core::result::Result<collections::string::String, ()>` does not implement any method in scope named `unwrap`
foo.rs:3     res.unwrap();
                 ^~~~~~~~
error: aborting due to previous error
```

**Comment by SimonSapin** [comment]
Oh, I see. For what it’s worth, there is some discussion in https://github.com/rust-lang/rfcs/pull/565 on reverting that change.

**Comment by renato-zannon** [comment]
[Seems like it will be reverted](https://github.com/rust-lang/rust/pull/21558). Good to know!

I think my first commit is still necessary though. Would you like me to submit another PR?

**Comment by SimonSapin** [comment]
No need. I’m in the middle of building Rust, since these changes are apparently not in Nightly yet.

**Comment by SimonSapin** [comment]
Alright, I’ve published v0.2.17 with your first commit. Tests are failing, but I expect this will be resolved when the `Result::unwrap` change is reverted.

**Comment by SimonSapin** [comment]
Oops, sorry, I got confused with rust-url.

**Comment by tomprogrammer** [comment]
The proposed changes in this PR were merged with e0c3c5e8 and published in version 0.2.4
